backend/api/models.py, backend/api/serializers.py, backend/api/urls.py, backend/api/views.py
Initialize the following:
~p.s. 看有沒有人想要用 [clean architecture](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html) 來開發，會多花一些時間在設計 interface ，不過以後要換 DB 或 framework (大推 Sanic) 會方便一些~先快糙猛的開發吧
=> [backend] init architecture

backend/README.md
=> [backend] add architecture image

.gitpod.dockerfile, .gitpod.yml, README.md
base on https://www.gitpod.io/blog/gitpodify documentation
=> Support gitpod for easier contribution

README.md, docs/gitpod.md
開 PR，賺 Hacktoberfest
https://hackmd.io/9JlnX61tSpGb0vsSJArGPQ
=> Add docs about how to use gitpod

backend/easymap.py
Problems in web requests to easymap are raised by `easymap.WebRequestError` exception.
=> Add error handling to easymap module

frontend/src/components/OSM.vue, frontend/src/lib/image.ts
=> 反轉農業用地的顏色，非農業黑色，農業透明

backend/Pipfile, backend/Pipfile.lock, backend/README.md, backend/api/migrations/0002_load_initial_data.py, backend/api/models.py, backend/api/tests.py, backend/api/tests/test_models.py
- ~`get nearby factory` test~
- ~`get nearby factory` impl~ (in next PR)
=> [Backend] DB initial data

backend/README.md, backend/docker-compose-win.yml
- update README
- add docker compose config for windows wsl
=> fix: add more build instructions

.circleci/config.yml, backend/Makefile
=> remove sudo from pipenv install

backend/api/views/factories_cr.py, backend/api/views/tests/test_factory_cr.py
fixed #57 
原先會把整個 DB 裡的 Image 都改到
=> Only modify factory ID foreign key of related images

backend/api/views/factories_cr.py, backend/api/views/tests/test_factory_cr.py
=> allow contact to be null when create factory

backend/Pipfile, backend/Pipfile.lock, backend/gis_project/settings.py
=> Backend cors

frontend/src/lib/map.ts
=> Gelocation recovery

frontend/src/App.vue, frontend/src/components/FilterModal.vue, frontend/src/components/FormPage.vue, frontend/src/components/Map.vue, frontend/src/lib/map.ts, frontend/src/symbols.ts
在用 main map controller 的地方的 `setup` hook:
```ts
const mapControllerRef = inject(MainMapControllerSymbol, ref<MapFactoryController>())
const mapController = mapControllerRef.value!
// do whatever you want ///
mapController.xxxxxx
```
=> Resuable map component

frontend/src/components/Map.vue, frontend/src/lib/map.ts
=> Add factory popup

frontend/src/App.vue, frontend/src/api/index.ts, frontend/src/components/FormPage.vue, frontend/src/components/ImageUploadModal.vue, frontend/src/components/Map.vue, frontend/src/lib/map.ts, frontend/src/styles/flex.scss, frontend/src/types.ts
part of #2
- 工廠名稱
- 工廠類型
- 其它資訊
=> Update factory fields

backend/api/views/factories_u.py
=> let update api be a proper view

frontend/src/components/Map.vue
=> Fix popup fake disable and #102

frontend/src/components/AppModal.vue, frontend/src/components/FilterModal.vue, frontend/src/components/FormPage.vue, frontend/src/styles/page.scss
=> Safari and iPhone safari fixes

frontend/src/components/FormPage.vue, frontend/src/components/Map.vue, frontend/src/lib/map.ts
=> minimap for factory form

frontend/src/App.vue, frontend/src/components/FormPage.vue, frontend/src/components/Map.vue, frontend/src/lib/map.ts
=> New create factory flow

frontend/src/components/Map.vue
=> Fix edit factory button won't work on iOS safari

frontend/src/components/FormPage.vue, frontend/src/lib/browserCheck.js, frontend/tsconfig.json, frontend/vue.config.js
=> Fix image upload on chrome

frontend/src/lib/map.ts
fix #138 
fix #136 
Add ScaleLine for #139
=> Fix rotation threshold and add change resolution

frontend/src/App.vue, frontend/src/components/FormPage.vue, frontend/src/components/ImageUploadModal.vue, frontend/src/components/Map.vue
fixes #127
fixes #134 
fixes #137
- ~~新增多張圖片 (safari)~~ 其實支援
- ~~上傳中 modal (aka THE NYAN)~~ 另外開 PR 弄好了
=> Revisit create factory mode

frontend/src/App.vue, frontend/src/api/index.ts, frontend/src/components/AppButton.vue, frontend/src/components/FormPage.vue, frontend/src/components/ImageUploadModal.vue, frontend/src/components/Map.vue, frontend/src/types.ts
=> Revise update factory flow

.circleci/config.yml, frontend/src/lib/map.ts
=> Fix not update features

frontend/src/components/FormPage.vue, frontend/src/components/Map.vue, frontend/src/lib/map.ts
=> Fix form validation

backend/api/views/factories_u.py, backend/api/views/tests/test_factories_u.py
=> disallow position update

backend/docker-compose.yml, backend/gis_project/settings.py
=> Feat/allowed host: multi allowed host support

frontend/src/components/FormPage.vue, frontend/src/types.ts
=> Modify factory type and sort

backend/api/views/factories_u.py
=> Solving issue 171, ready to test branch get_add_single_factory_api.

frontend/src/components/FormPage.vue, frontend/src/components/Map.vue, frontend/src/lib/useBackPressed.ts
=> Handle backpressd event

backend/api/views/factories_u.py, backend/api/views/tests/test_factories_u.py
=> Backend get single factory

frontend/src/components/AboutModal.vue, frontend/src/components/AppModal.vue, frontend/src/components/AppNavbar.vue, frontend/src/components/AppSidebar.vue, frontend/src/components/ContactModal.vue, frontend/src/components/GettingStartedModal.vue, frontend/src/components/SafetyModal.vue, frontend/src/styles/page.scss
=> 修正安全須知無法捲動問題

backend/Pipfile, backend/Pipfile.lock, backend/api/tasks.py, backend/api/tests/test_tasks.py, backend/api/views/factories_cr.py, backend/api/views/factory_image_c.py, backend/api/views/image_c.py, backend/api/views/tests/test_factory_cr.py, backend/api/views/tests/test_factory_image_c.py, backend/api/views/tests/test_image_c.py, backend/api/views/tests/test_utils.py, backend/api/views/utils.py, backend/gis_project/settings.py
用 DjangoQ 架構，讓地號非同步去要，可以大幅節省 create factory 的時間。從數秒 -> 半秒
deploy 的部份可能需要 @yellowsoar 協助，不太確定要怎麼改 `Procfile`
=> Backend async

README.md
`join.g0v.today` -> `join.g0v.tw`
=> Update g0v slack self-invitation link

backend/api/migrations/0002_load_initial_data.py, backend/docker-compose.yml
=> Bcakend fix some bugs

backend/api/views/factories_cr.py, backend/api/views/factories_u.py, backend/api/views/factory_image_c.py, backend/api/views/image_c.py, backend/gis_project/settings.py
== settings ==
LOGGING format : '%(asctime)s [%(levelname)s] %(message)s (%(module)s %(lineno)d)'
== Views ==
#creat_factory (trace)
Fail => warning : user_ip
Sucess => info : user_ip、(lng , lat)、factory_id、factory_name、factory_type
#update_factory (trace)
Fail => warning : client_ip
Sucess => info : client_ip、factory_id、put_body
#post_factory_image (trace)
Fail => warning : client_ip、factory_id
Sucess => info : client_ip、factory、factory_id、path
#post_image (trace)
Fail => warning : client_ip
Sucess => info : img.id、image_original_date
=> Extend logger

frontend/package-lock.json, frontend/package.json, frontend/src/App.vue, frontend/src/components/FormPage.vue, frontend/src/components/ImageUploadModal.vue, frontend/src/components/Map.vue, frontend/src/lib/appState.ts, frontend/src/lib/hooks.ts, frontend/src/lib/useGA.ts, frontend/src/main.ts, frontend/src/shims-vueGtags.ts
This reverts commit 45f9cfd122bc18d7ab2cde951aaf61c302740365.
=> Revert "Remove GA"

frontend/public/index.html, frontend/vue.config.js
=> Modify website title and og meta

frontend/src/components/Map.vue
=> Fix popup wrong position after open select mode

backend/.gitignore, backend/api/admin.py, backend/gis_project/settings.py
Basic admin page with some filtering and sorting on certain fields. Go to localhost:8000/admin for more info
related: #268
=> Backend admin page setup

backend/api/admin.py
related to #268
- 新增「輸出 csv 」的動作
- 可以過濾出有舉報紀錄的項目
=> export csv and filter with report record

frontend/src/components/AppButton.vue, frontend/src/components/AppTextField.vue, frontend/src/components/Map.vue, frontend/src/lib/map.ts, frontend/src/styles/flex.scss, frontend/src/styles/openlayer.scss
=> Navigate to input location

backend/api/admin.py
Now the admins can export csv of `Image` and `ReportRecord` table
=> make ReportRecord and Image csv-exportable

backend/api/admin.py
=> Better factory view for admin page

backend/api/admin.py
讓沒有名字的工廠也可以點到，並加回 factory type
=> let name clickable and add factory type

frontend/src/components/Map.vue
=> Set zoom to 17 if no zoom given or less than 17

backend/README.md, backend/api/admin/factory.py
admin page 可以根據縣市對 factory 做 filter 動作
=> feat(factory): filter factory by county

backend/Pipfile, backend/Pipfile.lock, backend/api/admin/factory.py, backend/gis_project/settings.py
- 加上第三方套件 rangefilter，可以根據 `updated_at` 來 filter factory 資料
- 重新排序 factory 的顯示
=> feat(factory): add rangefilter to filter factory by `updated_at`

backend/api/admin/factory.py
可以輸入，根據 townname 或 sectname 做進一步的 filter
=> feat(factory): add search_fields for column `townname` and `sectname`

frontend/src/App.vue, frontend/src/components/FormPage.vue, frontend/src/components/IOSVersionAlertModal.vue, frontend/src/lib/browserCheck.ts, frontend/src/lib/hooks.ts
=> Add ios version alert modal

backend/api/management/commands/reupload.py, backend/api/tasks.py, backend/api/tests/test_tasks.py
=> add a management command to upload all images that are not on Imgur

backend/api/migrations/0015_init_town_sect_name_code.py, backend/api/tasks.py
解決掉  migration 的時候會用到沒註冊的 Factory 的 bug
Huge thanks to TobyLiu for finding the bug
=> fix factory bug when migration

backend/Pipfile, backend/Pipfile.lock, backend/api/serializers.py, backend/api/urls.py, backend/api/views/factories_cr.py, backend/api/views/factories_u.py, backend/api/views/factory_image_c.py, backend/api/views/factory_report_record_r.py, backend/api/views/image_c.py, backend/api/views/tests/test_factory_cr.py, backend/gis_project/settings.py, backend/gis_project/urls.py
在 /swagger 與 /redoc 加入 swagger 與 redoc 的文件頁面
swagger
redoc
不過目前我沒有加入權限限制，是否需要加入可以登入後台的人才能用呢？
P.S.
formatter 有設定最多 100 字元了，可是有些還是因為太長改到了‧
所以就還是上傳上來了 .... 
不過應該比之前 80 字元還要少很多修改了
=> Add drf-swagger and swagger document

backend/Makefile, backend/README.md
更新 backend README 的文件，增加更多的開發環境描述以及只單獨啟動 db container 的方式，降低 db 安裝問題造成的門檻
=> Update backend README.md and makefile target 'run-db'

backend/api/admin/actions/export_docx.py
Fixed #378 
1. Change '正文' position
2. Remove debug message
=> Fixed #378 修正 "正文" 的位置與字體大小

backend/api/serializers.py, backend/api/tests/test_serializers.py
resolved #224 , now the API returns factory with display_number
=> add display_number in FactorySerializer

backend/api/serializers.py, backend/api/tests/test_serializers.py
=> add test allowing empty factory type

backend/api/views/factories_cr.py, backend/api/views/tests/test_factory_cr.py
=> allow factory type to be empty for API view

backend/.flake8, backend/api/serializers.py, backend/easymap.py, backend/users/models.py, backend/users/views.py
- 看 circleci 好像有要引入 flake8，先試改一些檔案
=> feat(flake8): use flake8 to lint files

backend/api/serializers.py
- 新的需求是想要在 call API `/factories` 的時候多拿一個欄位 `document_display_status`，這欄位的值是根據 factory 底下 `created_at` 是最新的 document 的 `display_status` 值
=> feat(api): return column `document_display_status` in `/factories` API

backend/api/admin/factory.py
close #407 
- 在 factory 頁面補上 reportrecord lastest created_at 並且可以根據此值排序
=> feat(factory): add column from latest repordrecord created_at

backend/api/admin/document.py, backend/api/models/__init__.py, backend/api/models/document.py
每次透過 admin 修改 display_status 時，寫一筆 FollowUp 註記 `舊狀態 -> 新狀態`
=> Display status history

backend/api/admin/factory.py
- fix typo
- search by display_number
=> feat: search by display_number and add display_number in fieldsets

backend/api/admin/factory.py
右邊的 filter 應該是根據 reportrecord_latest_created_at 這欄位才對
=> fix: should filter by reportrecord_latest_created_at

backend/api/views/miscellaneous/tests/test_factory_image_c.py, backend/api/views/miscellaneous/tests/test_image_c.py, backend/api/views/tests/test_factory_image_c.py, backend/api/views/tests/test_image_c.py, backend/gis_project/settings.py
=> use local timezone

backend/README.md
1. 更新 django 的版本
2. 移除 Gitpod (因為需要付費比較麻煩）
=> 更新 django 的連結到版本 2.0 以及移除 Gitpod 的說明（因為需要付費比較麻煩）

backend/Dockerfile, backend/docker-compose.dev.yml, backend/docker-compose.yml, backend/scripts/start.sh, backend/scripts/start_worker.sh, backend/scripts/wait-for-it.sh
增加 `scripts/start.sh` 與 `scripts/start_worker.sh` 讓 web 與 worker 的 container 透過這兩支 script 等待 postgreSQL 啟動。
=> 在 docker-compose 的 web 與 worker service command 中使用 wait-for-it 等待 postgreSQL 啟動完成

backend/api/admin/actions/export_csv.py, backend/api/admin/actions/export_docx.py, backend/api/admin/actions/export_label.py, backend/api/admin/actions/generate_docs.py, backend/api/admin/actions/restore.py, backend/api/admin/document.py, backend/api/admin/factory.py, backend/api/admin/test/test_actions.py, backend/api/models/document.py, backend/api/serializers.py, backend/api/tasks.py, backend/api/utils.py
一些潔癖型的修改
1. 一堆 function.short_description = ...
視覺雜訊太大了，用一個 decorater 做
2. 一些迴圈 or 條件改寫
3. 空行 換行 spacing 調整
4. 沒用的 ConvertToUpperCaseNumbers 拿掉，ConvertToLowerCaseNumbers 改名
=> Refactor misc

backend/.gitignore, backend/Pipfile, backend/Pipfile.lock, backend/api/admin/__init__.py, backend/api/admin/document.py, backend/api/admin/factory.py, backend/gis_project/settings.py
增加 django-import-export packages 讓使用者可以 import/export database 資料
=> Add django-import-export package

backend/api/admin/document.py
先寫死 width = 350
我 local 也沒工廠圖片，直接硬 merge 請 deeper 測測看？
=> limit document image width

.circleci/config.yml, backend/Dockerfile, backend/poetry.lock, backend/pyproject.toml
pipenv 的維護和易用性越來越不及 poetry 了，趁這個機會改一改
=> Use poetry

backend/.dockerignore, backend/Makefile
new make commands:
`logs`
`logs-dev`
`clean-dev` (remove containers and network)
no `clean` since it's dangerous to remove production container
=> add clean and logs command

backend/scripts/start_worker.sh
讓 server 跑就好，以免有 race condition
=> avoid worker running migration

backend/api/admin/factory.py
issue #435
`cet_report_status`->`cet_review_status`
=> replace admin factory filter:

backend/api/admin/document.py
=> let document edit admin page has more factory info

backend/api/admin/factory.py
=> feat: change google map preview to google map link

.circleci/config.yml
=> fix: change deprecated Pipfile.lock to poetry.lock

backend/api/admin/factory.py, backend/api/admin/image.py, backend/towninfo/__init__.py
後台經緯度修改後，重新從 easymap 取得地段資訊 Fixed #460
=> 後台經緯度修改後，重新從 easymap 取得地段資訊 Fixed #460

backend/.env.sample, backend/api/admin/factory.py
close #461 
- 完成替代方案： "有個連回disfactory.tw該點位的連結"
=> feat: add disfactory map link in admin factory page

backend/api/admin/actions/export_docx.py
=> fixed #466 - 公文聯絡電子信箱沒有隨名字更改

backend/api/admin/document.py
fix #468 
將 code, factory sectname 加入搜尋條件
使用 code 搜尋
使用段名搜尋
=> fix #468 document 搜尋需要 query 段名、公文號

backend/api/admin/document.py
@deeper747 許願的，剛好很容易做的功能：可以輸出公文的 csv
fixed #470
=> add csv export action for document

backend/api/admin/actions/generate_docs.py
=> feat: update factory.cet_review_status when generating documents

backend/api/admin/actions/export_docx.py, backend/api/models/report_record.py
=> ReportRecord's factory on_delete=CASCADE

backend/api/views/utils.py
close #302 , #18
- 只有這部份用到 postGIS，根據 issue #302 裡面提到的 [Haversine formula](https://stackoverflow.com/questions/574691/mysql-great-circle-distance-haversine-formula) 就能取代 postGIS 這部份提供的功能了，改寫之後應該就不需要 postGIS ㄌ
=> refactor(postGIS): use algorithm to calculate radius rather than postGIS

.github/workflows/tests.yml
測試的流程是從 CircleCI 的設定檔轉移過來的，目前是設定所有到 master 的 commit 以及 Pull Request 會觸發
=> 使用 Github Actions 來為每個 pull request 以及 push 到 master 的 commit 進行測試

backend/Makefile
=> add a hint about how to restore backup file

backend/api/admin/actions/generate_docs.py, backend/api/tests/test_utils.py, backend/api/utils.py, backend/api/views/statistics_r.py
=> add a util function for normalizing townname

backend/api/views/statistics_r.py
- `doc_num` 沒用到
- 計算數量的命名最好前綴 `n_`
=> slightly refactor statistics view function

backend/api/serializers.py, backend/api/views/utils.py
用大量的 Prefetch 來減少 `FactorySerializer` 對 DB query 的次數，在我本機測（SSD）可以快個兩倍多一點
用以下腳本在 shell 測試
```python
from cProfile import Profile
import pstats
from django.http import JsonResponse
from api.serializers import FactorySerializer
from api.views.utils import _get_nearby_factories
pr=Profile();pr.enable(); a = FactorySerializer(_get_nearby_factories(latitude=22.688508991021976, longitude=120.37539798859859, radius=5), many=True).data;pr.disable();ps = pstats.Stats(pr)
ps.sort_stats('tottime').print_stats(20)
```
before:
```
197461 function calls (191605 primitive calls) in 0.232 seconds
Ordered by: internal time
List reduced from 770 to 20 due to restriction <20>
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
202    0.059    0.000    0.061    0.000 {method 'execute' of …
```
=> use prefetch for query factories with serializer

.circleci/config.yml
- 把 frontend 的 circleci job 砍掉
=> chore: remove unused frontend ci job

backend/easymap.py
close #507 
- 在這邊就先拿出 cityCode，避免後面要用到的時候噴出的 error 會是取不到值，會比較難 debug
=> refactor: throw error if dont have cityCode

backend/docker-compose-win.yml, backend/docker-compose.dev.yml, backend/docker-compose.yml
=> feat: use official postgres image

backend/api/serializers.py, backend/api/views/tests/test_factory_cr.py
=> add source field to /factories API

backend/api/views/factory_image_c.py, backend/api/views/image_c.py
API 不檢查 image 內的 deletehash 欄位是否為空值
=> API 不檢查 image 內的 deletehash 欄位是否為空值

backend/api/admin/actions/__init__.py, backend/api/admin/actions/export_csv.py, backend/api/admin/document.py
=> feat: export new field 'townname', 'lat', 'lng' in document csv

backend/Dockerfile
- 這樣 build image 的時候就可以 cache poetry install 那部份了
=> feat: cache when docker build

.github/workflows/tests.yml, backend/poetry.lock, backend/pyproject.toml, backend/pytest.ini
讓 pytest 在執行的時候也會載入 .env 檔案，並且修改 github actions 的 test script，讓他也使用 pytest 來執行測試
=> Load .env when executing pytest

backend/README.md
更新  README 把關於 pipenv 的安裝換成 poetry
=> Replace pipenv with poetry

backend/api/admin/factory.py, backend/api/views/tests/test_easymap.py, backend/easymap.py
easymap 的 API 與 URL 都更換了，所以導致了 #460 的功能又失效。
=> 更新 easymap 的 URL

backend/api/admin/actions/export_docx.py
=> fix #541 公文年份應為民國

backend/users/admin.py, backend/users/forms.py
=> 修正 user admin page 無法儲存的問題

backend/README.md
在repository 中的此example檔案名稱為 .env.sample 而非 .env.example
可以改README 中的 description，或者考慮改檔案名稱（與frontend 一致）
=> README.md 解說檔案名稱改正

backend/api/models/const.py, backend/api/models/document.py, backend/api/views/statistics_r.py, backend/api/views/tests/test_statistics_r.py
Simply refactoring the hard-coded status string to reduce the code duplicate.
This commit is created in my forked repository, and contributed from the "downstream" community.
=> [Refactoring] Add const static variable for the hardcode status string

backend/api/views/tests/test_easymap.py, backend/docker-compose.yml, backend/easymap.py, backend/torrc
增加一個 proxy 的 container，透過 proxy 去取得資料
並且延長 easymap 的 timeout，
所以還需要確認一下 easymap 的呼叫不會 block api
=> 透過 rotating proxy 去取得資料

backend/api/serializers.py, backend/api/views/utils.py
先將 document 的 follow_up 讀出來，避免在 factory 量很大的時候，花費太多時間在查詢]
=> prefetch follow_ups to reduce SQL queries

backend/api/admin/factory.py
讓 admin 頁面可以用 factory id 搜尋 factory
=> user can search factory by factory id

backend/Dockerfile, backend/api/serializers.py, backend/api/urls.py, backend/api/views/__init__.py, backend/api/views/factory_location_r.py, backend/api/views/tests/test_factory_cr.py, backend/api/views/tests/test_factory_location.py, backend/towninfo/__init__.py
這個 API 不需要除了 Factory table 的資料之外，不需要 Document 與 ReportRecord 的資訊
應該可以加快 SpotDiff 使用 Factory ID 取工廠位置資訊的速度，
並且減輕 server 負擔
=> 增加 factory location api

backend/easymap.py
看起來應該是因為 requests 更新設定方式
現在需要指定 schema
=> fix proxy schema

.github/workflows/tests.yml
因為 easymap 開始擋國外 ip 的樣子，所以用 github action 跑會失敗
=> ignores test_easymap because easymap blocks foreign ip

.github/workflows/tests.yml
=> upgrade poetry to 1.2.0

backend/api/admin/factory.py, backend/api/admin/filters/duplicate_sect_land_filter.py
在工廠頁面增加 filter 列出有相同 sectcode 與 landcode 的工廠
=> Add filter to list factories with the same sectcode and landcode

backend/poetry.lock, backend/pyproject.toml, backend/scripts/convert_moea_data/convert.py
將流程改為先讀取全部的excel檔案，並依據地號或地址去重複後，再轉換sect-code
=> deduplicate factory data

backend/api/admin/factory.py, backend/api/admin/test/test_actions.py, backend/api/tasks.py, backend/api/views/tests/test_easymap.py, backend/docker-compose.yml, backend/easymap.py, backend/torrc
fix #631
用找到的新網站修理 easymap 封鎖 proxy 與國外 IP 沒有辦法用來查詢地號的問題
之後會想辦法在 Disfactory 自己的 server 上架設
=> Fix #631 無法透過 easymap 從經緯度取得地號的問題

backend/api/urls.py, backend/api/views/__init__.py, backend/api/views/statistics_r.py
=> Add action_change api

backend/api/admin/document.py
=> Allow filtering docs by gov response status tags

backend/api/admin/actions/__init__.py, backend/api/admin/actions/export_docx.py, backend/api/admin/actions/export_docx_using_js.py, backend/api/admin/document.py, backend/api/templates/admin/document/export_docx_using_js.html
使用 yukai 做的 https://github.com/Disfactory/docx-exporter-js 來從 client 產生公文。
因為 disfactory 的 server 已經被 imgur block 了，所以現在無法在 server 端產生有圖片的公文。
因此使用 client 避免這種情況發生。
=> Generate documents using docx.js.

backend/api/admin/actions/generate_docs.py
因為現在已經沒有分區域負責人了，所以直接用預設的就可以了
順便修正當 towname 為 None 的時候，會 crash 的問題
=> 因為現在已經沒有分區域負責人了，所以直接用預設的就可以了

backend/api/views/factories_cr.py, backend/api/views/tests/test_factory_cr.py, backend/api/views/utils.py
=> Display only the factory data uploaded by the user.

backend/Dockerfile, backend/docker-compose.dev.yml, backend/gis_project/settings.py, backend/scripts/start.sh, backend/scripts/start_worker.sh, zeabur.yaml
Enhance the Dockerfile and scripts for better static file management and ensure database migrations are included in the Disfactory worker startup command. Update icons to utilize frontend assets.
=> Improve static file handling and update worker commands

backend/gis_project/urls.py
Enhance URL routing by adding static file handling for both media and static files in the urlpatterns.
=> Add static file URL routing to urlpatterns
