Disfactory/Disfactory

backend/gis_project/urls.py
`/` redirect 到 https://dev.disfactory.tw/
fixed #81
=> redirect backend deafult url to dev page

frontend/src/components/Map.vue
related to #76 
手機版 safari 高度不能用 vh 去對要用 % 去對
=> Fix center pointer positioning

Procfile
This PR will activate django server via gunicorn instead of runserver.
The code has been deployed to middle2 and work as usual for now. XD
=> Activate django via gunicorn on middle2

frontend/src/App.vue, frontend/src/components/AboutModal.vue, frontend/src/components/FormPage.vue, frontend/src/components/Map.vue, frontend/src/lib/appState.ts, frontend/src/lib/factoryPopup.ts, frontend/src/lib/hooks.ts, frontend/src/lib/map.ts
fixes #183 (也就 6575824 這個 commit 相關而已)
試著用 provide/inject api 把一堆 global state 拆出來，讓他在另一個檔案亂（逃
順便用 global 的 factoryData state 把 popup 資料補充資料時不會更新的問題一併解掉
=> Fix popup state refreshing

backend/api/admin/actions/export_docx.py, backend/api/admin/test/test_actions.py
Thanks @stegben https://github.com/Disfactory/Disfactory/issues/323#issuecomment-691423661
Accroding to https://github.com/python-openxml/python-docx/issues/187
python-docx can't parse some jpeg files correctly, so we use PIL
to format all jpeg files to workaround this issue when generating docx
file.
=> Workaround python-docx bug https://github.com/python-openxml/python-docx/issues/187

backend/.env.sample, backend/Makefile, backend/docker-compose.dev.yml, backend/docker-compose.yml
指定 db mount 到主機 local 的某個資料夾，並另外設定一個 backup 的 mount。
新增一個 make command 可以執行備份：
`make run-db-backup`
下了之後備份檔就會出現在 `DISFACTORY_PGDATA_BACKUP_PATH`
=> setup local mount for db data and backup path

backend/api/admin/document.py, backend/api/admin/factory.py
Fix Issue #442 
在 factory change view 裡面列出該工廠的所有公文，並且使用者可以點擊公文文號開啟該公文的 document change view
在 document change view 中，使用者可以點擊工廠名稱開啟該工廠的 factory change view
=> Fix #442 在工廠編輯頁面增加公文的連結，在公文的編輯頁面增加工廠的連結

backend/api/serializers.py
=> remove sensitive fields from report record

backend/.env.sample, backend/Makefile
- 用 `COMPOSE_PROJECT_NAME` 來分離不同的 deploy. Fixed #449 
- 讓 makefile 真正的讀到環境變數
=> some deploy-friendly setting

backend/api/admin/actions/export_docx.py
在輸出 docx 檔的時候，完整的工廠位置名稱應該是
`<factory.townname><factory.sectname> (<factory.sectcode>) <factory.landcode> 地號`
e.g. `新北市雙溪區牡丹里武丹坑段五分小段  (1481) 00180000 地號`
其中 `武丹坑段五分小段` 就是之前漏掉沒有加上的地段名稱
=> 修正輸出的公文，地段名稱未出現的問題 #457

backend/api/views/factories_cr.py, backend/api/views/factories_u.py, backend/api/views/factory_image_c.py, backend/api/views/image_c.py, backend/api/views/miscellaneous/factory_image_c.py, backend/api/views/miscellaneous/image_c.py
提供 swagger 與 redoc 頁面，讓使用者可以比較方便理解 API 的使用方式
另外為了避免 API 太容易被攻擊，所以不顯示 Create 與 Update 的 API
=> Fix #226 與 #384 提供 swagger 與 redoc 讓使用者比較方便了解 API 的使用方式

backend/api/models/document.py, backend/api/models/image.py, backend/api/models/review.py
```
Image --> ReportRecord --> Factory
|                         ^
--------------------------
```
~Image 對 ReportRecord 設 restrict，如果刪 ReportRecord 不是因為他的 Factory 會刪
會 raise 一個 error~
~目前還沒有刪 ReportRecord 的需求，先上比較保護性質的設定~
RESTRICT 要 Django 3.1 才有，故用 CASCADE
Document 部分，跟 deeper confirm 過先設 SET_NULL
=> set on_delete for Factory related models

backend/api/views/statistics_r.py
因為有些 factories 的 towname 開頭是 `臺灣省花蓮縣` 有些則是 `花蓮縣` 
所以之前是使用 `contains` 的方式來搜尋 townname。
但是這個效能很差，所以改用兩個 `startswith` 的 filter 來處理，也就是同時搜尋 `臺灣省花蓮縣` 與 `花蓮縣` 
在我的電腦上這樣效能就可以從 14s 縮短到 4s 左右
=> 改善 `/api/statistics/factories?level=town` 的效能

backend/docs/SETUP_COMPOSE.md
According to c66fee554f4bf033fa776d9701334c860acb2bc1 , it seems the current unittest is launched by `pytest` instead of `manage.py test`.
1. Launch the dev environment with docker-compose, e.g. `make run-dev`
2. `docker-compose exec web pytest`
`55 passed, 25 warnings`
`docker-compose exec web python manage.py test` does not do anything. Its output is:
```
localhost,127.0.0.1
System check identified no issues (0 silenced).
----------------------------------------------------------------------
Ran 0 tests in 0.000s
OK
```
=> docs(docker-compose): update the test command

backend/api/views/tests/test_easymap.py, backend/easymap.py
easymap 原本用的 URL 會發生 `Opppps..網頁發生錯誤,請洽管理人員` 的錯誤，
因此換成 P02 系列手機用的網頁 URL 避免這個問題
=> Update easymap url to workaround easymap server error

.github/workflows/tests.yml, backend/Dockerfile
The previous poetry installer is deprecated, so we need to migrate to https://install.python-poetry.org instead
=> update poetry installation

backend/poetry.lock, backend/pyproject.toml
Update the dev dependencies due to 
* The typed-ast lib used by black conflicts with the current python version
* poetry `dev-dependencies` notation will be soon deprecated
=> update poetry dev-dependencies

backend/api/views/utils.py
Use Greatest and Least functions to clamp the cosine value between -1 and 1 before applying ACos. This prevents errors when rounding errors cause the value to be slightly outside the valid range.
=> Fix distance calculation for nearby factories

backend/api/admin/factory.py
當 easymap 回傳值是空的時候，就不要更新工廠資料。
否則會導致使用者無法手動設定資料。
=> If the return value of easymap is empty, do not update.

backend/api/admin/actions/export_docx.py
imgur 現在很容易就觸發到使用上限，只好忽略他了。先讓 doc 公文能正常產生
=> ignore http error code when downloading image files from imgur
